---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.18.1
  ansible_runner:
    package_pip: ansible-runner
  galaxy: files/requirements.yml
  python: files/requirements.txt
  system: files/sysdep.txt
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip wheel setuptools
    - RUN $PYCMD -m pip install python-core
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
options:
  user: root
