---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: awx.awx
      - name: amazon.aws
      - name: google.cloud
      - name: community.vmware
      - name: kubernetes.core
      - name: ansible.posix
      - name: ansible.windows
      - name: community.zabbix
      - name: community.general
      - name: junipernetworks.junos
      - name: community.mongodb
      - name: community.kubernetes
      - name: ansible.netcommon
      - name: community.postgresql
      - name: community.docker
      - name: community.aws
      - name: community.mysql
      - name: community.grafana
      - name: community.windows
      - name: community.crypto
      - name: dellemc.openmanage
  system: |
    epel-release
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
    python3-netaddr [platform: rpm]
    sudo [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pyyaml
    six
    netaddr
    google-auth
    zabbix-api
    boto
    boto3
    botocore
    pexpect
    prettytable
    ntplib
    python-daemon
    jmespath
    junos-eznc
    jxmlease
    ncclient==0.6.4
    cryptography==3.3.1
    jmespath
    passlib
    pysphere
    pyvmomi
    docker
    docker-compose
    omsdk
    pysnmp>=4.4.1
    requests>=2.12.3
    PyYAML==5.3.1
    future>=0.16.0
    pysnmp_mibs>=0
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
options:
  user: root
